### ISSUE TITLE
NoFound model of f

### ISSUE THREAD

**Issue by meikobay** [jyf588/SimGAN#1]
(The first command in each script runs Hybrid Simulator Identification as listed in Algorithm 1 of the paper, while the second command runs the Policy Refinement part as listed in Algorithm 1)
but no hybrid simulator network is found in [main_gail_dyn_ppo.py](https://github.com/jyf588/SimGAN/blob/master/third_party/a2c_ppo_acktr/main_gail_dyn_ppo.py). I know I have lose some important code, please tell me, Thank You!!!

**Comment by jyf588** [comment]
my_pybullet_envs/hopper_env_combined_policy.py and third_party/a2c_ppo_acktr/model_split.py defines the analytical and learned components of the hybrid simulator respectively. You could also take a look at the Notes section of the Readme file. Thanks!
